function flujosorigen = importflujo(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FLUJOSORIGEN1 = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a cell array.
%
%  FLUJOSORIGEN1 = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  flujosorigen1 = importfile("/Users/mrebollo/devel/taskforce/mobilitynet/flujos_origen.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2020 16:04:31

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 5);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["target", "NOMBRE_CELDA_DESTINO", "source", "NOMBRE_CELDA_ORIGEN", "FLUJO"];
opts.VariableTypes = ["string", "string", "string", "string", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["target", "NOMBRE_CELDA_DESTINO", "source", "NOMBRE_CELDA_ORIGEN"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["target", "NOMBRE_CELDA_DESTINO", "source", "NOMBRE_CELDA_ORIGEN"], "EmptyFieldRule", "auto");

% Import the data
flujosorigen = readtable(filename, opts);

%% Convert to output type
flujosorigen = table2cell(flujosorigen);
numIdx = cellfun(@(x) ~isnan(str2double(x)), flujosorigen);
flujosorigen(numIdx) = cellfun(@(x) {str2double(x)}, flujosorigen(numIdx));
end