function zonasine = importzonas(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ZONASINE1 = IMPORTFILE(FILENAME) reads data from text file FILENAME
%  for the default selection.  Returns the data as a cell array.
%
%  ZONASINE1 = IMPORTFILE(FILE, DATALINES) reads data for the specified
%  row interval(s) of text file FILENAME. Specify DATALINES as a
%  positive scalar integer or a N-by-2 array of positive scalar integers
%  for dis-contiguous row intervals.
%
%  Example:
%  zonasine1 = importfile("/Users/mrebollo/devel/taskforce/mobilitynet/zonas_ine.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Apr-2020 16:03:52

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["code", "name", "X", "Y"];
opts.VariableTypes = ["string", "string", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["code", "name"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["code", "name"], "EmptyFieldRule", "auto");

% Import the data
zonasine = readtable(filename, opts);

%% Convert to output type
zonasine = table2cell(zonasine);
numIdx = cellfun(@(x) ~isnan(str2double(x)), zonasine);
zonasine(numIdx) = cellfun(@(x) {str2double(x)}, zonasine(numIdx));
end